apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-env
data:
  # Inclure ici les variables d'environnement de ./gateway/.env
  USERS_SERVICE_UR  : http://users-service:{{ .Values.usersService.service.port }}
  ORDERS_SERVICE_URL: http://orders-service:{{ .Values.ordersService.service.port }}