apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  type: {{ .Values.ordersService.service.type }}
  ports:
    - port: {{ .Values.ordersService.service.port }}
      targetPort: {{ .Values.ordersService.service.targetPort }}
      nodePort: {{ .Values.ordersService.service.nodePort }}        
  selector:
    app: orders-service
