apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-service-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
  storageClassName: local-path      
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-service-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
  storageClassName: local-path      
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-service-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
  storageClassName: local-path

